micronaut:
  application:
    name: micronaut-petclinic
  server:
    port: 8080
  router:
    static-resources:
      default:
        enabled: true
        mapping: /resources/**
        paths: classpath:static
  caches:
    vets:
      expire-after-write: 60s
      maximum-size: 100
  views:
    jte:
      dynamic: false
      binary-static-content: true
  messages:
    basename: i18n/messages

# Sample data configuration
petclinic:
  sample-data:
    enabled: true

# Logging configuration
logger:
  levels:
    io.micronaut.samples.petclinic: DEBUG
    io.micronaut.data: DEBUG

endpoints:
  info:
    sensitive: false
  health:
    details-visible: authenticated
    jdbc:
      enabled: true

info:
  application:
    name: ${micronaut.application.name}
