-- Initialize the PetClinic schema and sample data for the DeepSec profile.
--
-- This is the SQL equivalent of DataLoader.

WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
SET VERIFY OFF
SET SERVEROUTPUT ON

-- The setup container connects to the local petclinic user in FREEPDB1.
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE SPECIALTIES (
      ID NUMBER(10,0) NOT NULL,
      NAME VARCHAR2(255) NOT NULL,
      CONSTRAINT PK_SPECIALTIES PRIMARY KEY (ID)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE VETS (
      ID NUMBER(10,0) NOT NULL,
      FIRST_NAME VARCHAR2(255) NOT NULL,
      LAST_NAME VARCHAR2(255) NOT NULL,
      CONSTRAINT PK_VETS PRIMARY KEY (ID)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE TYPES (
      ID NUMBER(10,0) NOT NULL,
      NAME VARCHAR2(255) NOT NULL,
      CONSTRAINT PK_TYPES PRIMARY KEY (ID)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE OWNERS (
      ID NUMBER(10,0) NOT NULL,
      FIRST_NAME VARCHAR2(255) NOT NULL,
      LAST_NAME VARCHAR2(255) NOT NULL,
      ADDRESS VARCHAR2(255) NOT NULL,
      CITY VARCHAR2(255) NOT NULL,
      TELEPHONE VARCHAR2(255) NOT NULL,
      CONSTRAINT PK_OWNERS PRIMARY KEY (ID)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE PETS (
      ID NUMBER(10,0) NOT NULL,
      NAME VARCHAR2(255) NOT NULL,
      BIRTH_DATE DATE NOT NULL,
      TYPE_ID NUMBER(10,0) NOT NULL,
      OWNER_ID NUMBER(10,0) NOT NULL,
      CONSTRAINT PK_PETS PRIMARY KEY (ID)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE VISITS (
      ID NUMBER(10,0) NOT NULL,
      VISIT_DATE DATE NOT NULL,
      DESCRIPTION VARCHAR2(255) NOT NULL,
      PET_ID NUMBER(10,0) NOT NULL,
      DURATION INTERVAL DAY(9) TO SECOND(9),
      FOLLOW_UP_PERIOD INTERVAL YEAR(9) TO MONTH,
      CONSTRAINT PK_VISITS PRIMARY KEY (ID)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE VET_SPECIALTIES (
      VET_ID NUMBER(10,0) NOT NULL,
      SPECIALTY_ID NUMBER(10,0) NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE CLINICS (
      ID NUMBER(10,0) NOT NULL,
      NAME VARCHAR2(255) NOT NULL,
      ADDRESS VARCHAR2(255) NOT NULL,
      CITY VARCHAR2(255) NOT NULL,
      LOCATION MDSYS.SDO_GEOMETRY NOT NULL,
      SERVICE_AREA MDSYS.SDO_GEOMETRY NOT NULL,
      CONSTRAINT PK_CLINICS PRIMARY KEY (ID)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- These columns were added to Visit after the first Oracle schema was created.
-- Add them when upgrading an older local DeepSec volume.
DECLARE
  v_column_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_column_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'VISITS' AND COLUMN_NAME = 'DURATION';
  IF v_column_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE VISITS ADD (DURATION INTERVAL DAY(9) TO SECOND(9))';
  END IF;

  SELECT COUNT(*) INTO v_column_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'VISITS' AND COLUMN_NAME = 'FOLLOW_UP_PERIOD';
  IF v_column_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE VISITS ADD (FOLLOW_UP_PERIOD INTERVAL YEAR(9) TO MONTH)';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SPECIALTIES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE VETS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE TYPES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE OWNERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE PETS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE VISITS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE CLINICS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- The insert order follows DataLoader: reference data, vets, pet types,
-- owners/pets, visits, and clinics.
DECLARE
  v_owner_count NUMBER;
  v_radiology NUMBER;
  v_surgery NUMBER;
  v_dentistry NUMBER;
  v_cat NUMBER;
  v_dog NUMBER;
  v_lizard NUMBER;
  v_snake NUMBER;
  v_bird NUMBER;
  v_hamster NUMBER;
  v_george NUMBER;
  v_betty NUMBER;
  v_eduardo NUMBER;
  v_harold NUMBER;
  v_peter NUMBER;
  v_jean NUMBER;
  v_jeff NUMBER;
  v_maria NUMBER;
  v_david NUMBER;
  v_carlos NUMBER;
  v_leo NUMBER;
  v_basil NUMBER;
  v_jewel NUMBER;
  v_rosy NUMBER;
  v_iggy NUMBER;
  v_george_pet NUMBER;
  v_samantha NUMBER;
  v_max NUMBER;
  v_lucky NUMBER;
  v_mulligan NUMBER;
  v_freddy NUMBER;
  v_lucky_carlos NUMBER;
  v_sly NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_owner_count FROM OWNERS;
  IF v_owner_count > 0 THEN
    DBMS_OUTPUT.PUT_LINE('PetClinic sample data already exists; migration skipped.');
    RETURN;
  END IF;

  INSERT INTO SPECIALTIES (ID, NAME) VALUES (SPECIALTIES_SEQ.NEXTVAL, 'radiology');
  INSERT INTO SPECIALTIES (ID, NAME) VALUES (SPECIALTIES_SEQ.NEXTVAL, 'surgery');
  INSERT INTO SPECIALTIES (ID, NAME) VALUES (SPECIALTIES_SEQ.NEXTVAL, 'dentistry');
  SELECT ID INTO v_radiology FROM SPECIALTIES WHERE NAME = 'radiology';
  SELECT ID INTO v_surgery FROM SPECIALTIES WHERE NAME = 'surgery';
  SELECT ID INTO v_dentistry FROM SPECIALTIES WHERE NAME = 'dentistry';

  INSERT INTO VETS (ID, FIRST_NAME, LAST_NAME) VALUES (VETS_SEQ.NEXTVAL, 'James', 'Carter');
  INSERT INTO VETS (ID, FIRST_NAME, LAST_NAME) VALUES (VETS_SEQ.NEXTVAL, 'Helen', 'Leary');
  INSERT INTO VETS (ID, FIRST_NAME, LAST_NAME) VALUES (VETS_SEQ.NEXTVAL, 'Linda', 'Douglas');
  INSERT INTO VETS (ID, FIRST_NAME, LAST_NAME) VALUES (VETS_SEQ.NEXTVAL, 'Rafael', 'Ortega');
  INSERT INTO VETS (ID, FIRST_NAME, LAST_NAME) VALUES (VETS_SEQ.NEXTVAL, 'Henry', 'Stevens');
  INSERT INTO VETS (ID, FIRST_NAME, LAST_NAME) VALUES (VETS_SEQ.NEXTVAL, 'Sharon', 'Jenkins');

  INSERT INTO VET_SPECIALTIES (VET_ID, SPECIALTY_ID)
  SELECT ID, v_radiology FROM VETS WHERE FIRST_NAME = 'Helen' AND LAST_NAME = 'Leary';
  INSERT INTO VET_SPECIALTIES (VET_ID, SPECIALTY_ID)
  SELECT ID, v_surgery FROM VETS WHERE FIRST_NAME = 'Linda' AND LAST_NAME = 'Douglas';
  INSERT INTO VET_SPECIALTIES (VET_ID, SPECIALTY_ID)
  SELECT ID, v_dentistry FROM VETS WHERE FIRST_NAME = 'Linda' AND LAST_NAME = 'Douglas';
  INSERT INTO VET_SPECIALTIES (VET_ID, SPECIALTY_ID)
  SELECT ID, v_surgery FROM VETS WHERE FIRST_NAME = 'Rafael' AND LAST_NAME = 'Ortega';
  INSERT INTO VET_SPECIALTIES (VET_ID, SPECIALTY_ID)
  SELECT ID, v_radiology FROM VETS WHERE FIRST_NAME = 'Henry' AND LAST_NAME = 'Stevens';

  INSERT INTO TYPES (ID, NAME) VALUES (TYPES_SEQ.NEXTVAL, 'cat');
  INSERT INTO TYPES (ID, NAME) VALUES (TYPES_SEQ.NEXTVAL, 'dog');
  INSERT INTO TYPES (ID, NAME) VALUES (TYPES_SEQ.NEXTVAL, 'lizard');
  INSERT INTO TYPES (ID, NAME) VALUES (TYPES_SEQ.NEXTVAL, 'snake');
  INSERT INTO TYPES (ID, NAME) VALUES (TYPES_SEQ.NEXTVAL, 'bird');
  INSERT INTO TYPES (ID, NAME) VALUES (TYPES_SEQ.NEXTVAL, 'hamster');
  SELECT ID INTO v_cat FROM TYPES WHERE NAME = 'cat';
  SELECT ID INTO v_dog FROM TYPES WHERE NAME = 'dog';
  SELECT ID INTO v_lizard FROM TYPES WHERE NAME = 'lizard';
  SELECT ID INTO v_snake FROM TYPES WHERE NAME = 'snake';
  SELECT ID INTO v_bird FROM TYPES WHERE NAME = 'bird';
  SELECT ID INTO v_hamster FROM TYPES WHERE NAME = 'hamster';

  INSERT INTO OWNERS (ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE)
  VALUES (OWNERS_SEQ.NEXTVAL, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
  INSERT INTO OWNERS (ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE)
  VALUES (OWNERS_SEQ.NEXTVAL, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
  INSERT INTO OWNERS (ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE)
  VALUES (OWNERS_SEQ.NEXTVAL, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
  INSERT INTO OWNERS (ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE)
  VALUES (OWNERS_SEQ.NEXTVAL, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
  INSERT INTO OWNERS (ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE)
  VALUES (OWNERS_SEQ.NEXTVAL, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
  INSERT INTO OWNERS (ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE)
  VALUES (OWNERS_SEQ.NEXTVAL, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
  INSERT INTO OWNERS (ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE)
  VALUES (OWNERS_SEQ.NEXTVAL, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
  INSERT INTO OWNERS (ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE)
  VALUES (OWNERS_SEQ.NEXTVAL, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
  INSERT INTO OWNERS (ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE)
  VALUES (OWNERS_SEQ.NEXTVAL, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
  INSERT INTO OWNERS (ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, TELEPHONE)
  VALUES (OWNERS_SEQ.NEXTVAL, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');
  SELECT ID INTO v_george FROM OWNERS WHERE FIRST_NAME = 'George' AND LAST_NAME = 'Franklin';
  SELECT ID INTO v_betty FROM OWNERS WHERE FIRST_NAME = 'Betty' AND LAST_NAME = 'Davis';
  SELECT ID INTO v_eduardo FROM OWNERS WHERE FIRST_NAME = 'Eduardo' AND LAST_NAME = 'Rodriquez';
  SELECT ID INTO v_harold FROM OWNERS WHERE FIRST_NAME = 'Harold' AND LAST_NAME = 'Davis';
  SELECT ID INTO v_peter FROM OWNERS WHERE FIRST_NAME = 'Peter' AND LAST_NAME = 'McTavish';
  SELECT ID INTO v_jean FROM OWNERS WHERE FIRST_NAME = 'Jean' AND LAST_NAME = 'Coleman';
  SELECT ID INTO v_jeff FROM OWNERS WHERE FIRST_NAME = 'Jeff' AND LAST_NAME = 'Black';
  SELECT ID INTO v_maria FROM OWNERS WHERE FIRST_NAME = 'Maria' AND LAST_NAME = 'Escobito';
  SELECT ID INTO v_david FROM OWNERS WHERE FIRST_NAME = 'David' AND LAST_NAME = 'Schroeder';
  SELECT ID INTO v_carlos FROM OWNERS WHERE FIRST_NAME = 'Carlos' AND LAST_NAME = 'Estaban';

  INSERT INTO PETS (ID, NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
  VALUES (PETS_SEQ.NEXTVAL, 'Leo', DATE '2010-09-07', v_cat, v_george);
  INSERT INTO PETS (ID, NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
  VALUES (PETS_SEQ.NEXTVAL, 'Basil', DATE '2012-08-06', v_hamster, v_betty);
  INSERT INTO PETS (ID, NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
  VALUES (PETS_SEQ.NEXTVAL, 'Jewel', DATE '2010-03-07', v_dog, v_eduardo);
  INSERT INTO PETS (ID, NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
  VALUES (PETS_SEQ.NEXTVAL, 'Rosy', DATE '2011-04-17', v_dog, v_eduardo);
  INSERT INTO PETS (ID, NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
  VALUES (PETS_SEQ.NEXTVAL, 'Iggy', DATE '2010-11-30', v_lizard, v_harold);
  INSERT INTO PETS (ID, NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
  VALUES (PETS_SEQ.NEXTVAL, 'George', DATE '2010-01-20', v_snake, v_peter);
  INSERT INTO PETS (ID, NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
  VALUES (PETS_SEQ.NEXTVAL, 'Samantha', DATE '2012-09-04', v_cat, v_jean);
  INSERT INTO PETS (ID, NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
  VALUES (PETS_SEQ.NEXTVAL, 'Max', DATE '2012-09-04', v_cat, v_jean);
  INSERT INTO PETS (ID, NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
  VALUES (PETS_SEQ.NEXTVAL, 'Lucky', DATE '2011-08-06', v_bird, v_jeff);
  INSERT INTO PETS (ID, NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
  VALUES (PETS_SEQ.NEXTVAL, 'Mulligan', DATE '2007-02-24', v_dog, v_maria);
  INSERT INTO PETS (ID, NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
  VALUES (PETS_SEQ.NEXTVAL, 'Freddy', DATE '2010-03-09', v_bird, v_david);
  INSERT INTO PETS (ID, NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
  VALUES (PETS_SEQ.NEXTVAL, 'Lucky', DATE '2010-06-24', v_dog, v_carlos);
  INSERT INTO PETS (ID, NAME, BIRTH_DATE, TYPE_ID, OWNER_ID)
  VALUES (PETS_SEQ.NEXTVAL, 'Sly', DATE '2012-06-08', v_cat, v_carlos);
  SELECT ID INTO v_leo FROM PETS WHERE NAME = 'Leo' AND OWNER_ID = v_george;
  SELECT ID INTO v_basil FROM PETS WHERE NAME = 'Basil' AND OWNER_ID = v_betty;
  SELECT ID INTO v_jewel FROM PETS WHERE NAME = 'Jewel' AND OWNER_ID = v_eduardo;
  SELECT ID INTO v_rosy FROM PETS WHERE NAME = 'Rosy' AND OWNER_ID = v_eduardo;
  SELECT ID INTO v_iggy FROM PETS WHERE NAME = 'Iggy' AND OWNER_ID = v_harold;
  SELECT ID INTO v_george_pet FROM PETS WHERE NAME = 'George' AND OWNER_ID = v_peter;
  SELECT ID INTO v_samantha FROM PETS WHERE NAME = 'Samantha' AND OWNER_ID = v_jean;
  SELECT ID INTO v_max FROM PETS WHERE NAME = 'Max' AND OWNER_ID = v_jean;
  SELECT ID INTO v_lucky FROM PETS WHERE NAME = 'Lucky' AND OWNER_ID = v_jeff;
  SELECT ID INTO v_mulligan FROM PETS WHERE NAME = 'Mulligan' AND OWNER_ID = v_maria;
  SELECT ID INTO v_freddy FROM PETS WHERE NAME = 'Freddy' AND OWNER_ID = v_david;
  SELECT ID INTO v_lucky_carlos FROM PETS WHERE NAME = 'Lucky' AND OWNER_ID = v_carlos;
  SELECT ID INTO v_sly FROM PETS WHERE NAME = 'Sly' AND OWNER_ID = v_carlos;

  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2026-01-05', 'rabies shot', v_samantha, NUMTODSINTERVAL(30, 'MINUTE'), NUMTOYMINTERVAL(6, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2026-01-15', 'neutered', v_samantha, NUMTODSINTERVAL(1, 'HOUR'), NUMTOYMINTERVAL(12, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2026-01-09', 'rabies shot', v_max, NUMTODSINTERVAL(15, 'MINUTE'), NUMTOYMINTERVAL(3, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2026-01-12', 'neutered', v_max, NUMTODSINTERVAL(2, 'HOUR'), NUMTOYMINTERVAL(24, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2017-02-08', 'annual wellness exam', v_leo, NUMTODSINTERVAL(15, 'MINUTE'), NUMTOYMINTERVAL(1, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2018-02-14', 'vaccination', v_basil, NUMTODSINTERVAL(45, 'MINUTE'), NUMTOYMINTERVAL(6, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2019-03-01', 'dental cleaning', v_jewel, NUMTODSINTERVAL(75, 'MINUTE'), NUMTOYMINTERVAL(9, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2020-03-15', 'ear infection', v_rosy, NUMTODSINTERVAL(90, 'MINUTE'), NUMTOYMINTERVAL(18, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2021-04-02', 'skin check', v_iggy, NUMTODSINTERVAL(120, 'MINUTE'), NUMTOYMINTERVAL(12, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2022-05-10', 'routine checkup', v_george_pet, NUMTODSINTERVAL(150, 'MINUTE'), NUMTOYMINTERVAL(24, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2023-06-18', 'wing injury', v_lucky, NUMTODSINTERVAL(20, 'MINUTE'), NUMTOYMINTERVAL(3, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2024-07-22', 'arthritis review', v_mulligan, NUMTODSINTERVAL(180, 'MINUTE'), NUMTOYMINTERVAL(36, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2025-08-09', 'follow-up examination', v_freddy, NUMTODSINTERVAL(30, 'MINUTE'), NUMTOYMINTERVAL(6, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2026-01-12', 'vaccination', v_lucky_carlos, NUMTODSINTERVAL(60, 'MINUTE'), NUMTOYMINTERVAL(12, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2026-06-21', 'dental cleaning', v_sly, NUMTODSINTERVAL(210, 'MINUTE'), NUMTOYMINTERVAL(18, 'MONTH'));
  INSERT INTO VISITS (ID, VISIT_DATE, DESCRIPTION, PET_ID, DURATION, FOLLOW_UP_PERIOD)
  VALUES (VISITS_SEQ.NEXTVAL, DATE '2026-08-25', 'allergy consultation', v_max, NUMTODSINTERVAL(45, 'MINUTE'), NUMTOYMINTERVAL(6, 'MONTH'));

  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'Downtown Madison Pet Clinic', '15 E Main St.', 'Madison',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.3838, 43.0748, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.3938, 43.0668, -89.3938, 43.0828, -89.3738, 43.0828, -89.3738, 43.0668, -89.3938, 43.0668)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'Capitol Square Pet Clinic', '2 S Carroll St.', 'Madison',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.3844, 43.0742, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.3944, 43.0662, -89.3944, 43.0822, -89.3744, 43.0822, -89.3744, 43.0662, -89.3944, 43.0662)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'University Pet Clinic', '750 University Ave.', 'Madison',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.3985, 43.0739, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.4085, 43.0659, -89.4085, 43.0819, -89.3885, 43.0819, -89.3885, 43.0659, -89.4085, 43.0659)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'East Madison Pet Clinic', '2210 E Washington Ave.', 'Madison',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.3545, 43.1020, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.3645, 43.0940, -89.3645, 43.1100, -89.3445, 43.1100, -89.3445, 43.0940, -89.3645, 43.0940)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'South Madison Pet Clinic', '2300 S Park St.', 'Madison',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.3952, 43.0384, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.4052, 43.0304, -89.4052, 43.0464, -89.3852, 43.0464, -89.3852, 43.0304, -89.4052, 43.0304)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'West Madison Pet Clinic', '701 N High Point Rd.', 'Madison',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.5186, 43.0753, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.5286, 43.0673, -89.5286, 43.0833, -89.5086, 43.0833, -89.5086, 43.0673, -89.5286, 43.0673)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'Middleton Pet Clinic', '7428 University Ave.', 'Middleton',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.5137, 43.0972, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.5237, 43.0892, -89.5237, 43.1052, -89.5037, 43.1052, -89.5037, 43.0892, -89.5237, 43.0892)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'Fitchburg Pet Clinic', '5515 Nobel Dr.', 'Fitchburg',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.4233, 43.0026, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.4333, 42.9946, -89.4333, 43.0106, -89.4133, 43.0106, -89.4133, 42.9946, -89.4333, 42.9946)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'Monona Pet Clinic', '6000 Monona Dr.', 'Monona',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.3240, 43.0622, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.3340, 43.0542, -89.3340, 43.0702, -89.3140, 43.0702, -89.3140, 43.0542, -89.3340, 43.0542)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'McFarland Pet Clinic', '4910 Terminal Dr.', 'McFarland',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.2887, 43.0125, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.2987, 43.0045, -89.2987, 43.0205, -89.2787, 43.0205, -89.2787, 43.0045, -89.2987, 43.0045)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'Sun Prairie Pet Clinic', '300 E Main St.', 'Sun Prairie',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.2137, 43.1836, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.2237, 43.1756, -89.2237, 43.1916, -89.2037, 43.1916, -89.2037, 43.1756, -89.2237, 43.1756)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'Waunakee Pet Clinic', '100 W Main St.', 'Waunakee',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.4557, 43.1919, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.4657, 43.1839, -89.4657, 43.1999, -89.4457, 43.1999, -89.4457, 43.1839, -89.4657, 43.1839)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'Verona Pet Clinic', '101 W Verona Ave.', 'Verona',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.5332, 42.9908, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.5432, 42.9828, -89.5432, 42.9988, -89.5232, 42.9988, -89.5232, 42.9828, -89.5432, 42.9828)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'Stoughton Pet Clinic', '207 S Forrest St.', 'Stoughton',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.2179, 42.9169, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.2279, 42.9089, -89.2279, 42.9249, -89.2079, 42.9249, -89.2079, 42.9089, -89.2279, 42.9089)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'Oregon Pet Clinic', '117 Spring St.', 'Oregon',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.3848, 42.9261, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.3948, 42.9181, -89.3948, 42.9341, -89.3748, 42.9341, -89.3748, 42.9181, -89.3948, 42.9181)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'DeForest Pet Clinic', '120 S Stevenson St.', 'DeForest',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.3440, 43.2478, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.3540, 43.2398, -89.3540, 43.2558, -89.3340, 43.2558, -89.3340, 43.2398, -89.3540, 43.2398)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'Mount Horeb Pet Clinic', '138 E Main St.', 'Mount Horeb',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.7385, 43.0086, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.7485, 43.0006, -89.7485, 43.0166, -89.7285, 43.0166, -89.7285, 43.0006, -89.7485, 43.0006)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'Portage Pet Clinic', '117 W Cook St.', 'Portage',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.4626, 43.5391, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.4726, 43.5311, -89.4726, 43.5471, -89.4526, 43.5471, -89.4526, 43.5311, -89.4726, 43.5311)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'Janesville Pet Clinic', '20 S Main St.', 'Janesville',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-89.0187, 42.6828, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-89.0287, 42.6748, -89.0287, 42.6908, -89.0087, 42.6908, -89.0087, 42.6748, -89.0287, 42.6748)));
  INSERT INTO CLINICS (ID, NAME, ADDRESS, CITY, LOCATION, SERVICE_AREA)
  VALUES (CLINICS_SEQ.NEXTVAL, 'Milwaukee Pet Clinic', '200 E Wells St.', 'Milwaukee',
    MDSYS.SDO_GEOMETRY(2001, 4326, MDSYS.SDO_POINT_TYPE(-87.9065, 43.0410, NULL), NULL, NULL),
    MDSYS.SDO_GEOMETRY(2003, 4326, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1),
      MDSYS.SDO_ORDINATE_ARRAY(-87.9165, 43.0330, -87.9165, 43.0490, -87.8965, 43.0490, -87.8965, 43.0330, -87.9165, 43.0330)));

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('PetClinic schema and sample data initialized.');
END;
/

-- Match the spatial indexes generated by the Clinic entity's @Index metadata.
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_CLINICS_LOCATION ON CLINICS (LOCATION) INDEXTYPE IS MDSYS.SPATIAL_INDEX';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_CLINICS_SERVICE_AREA ON CLINICS (SERVICE_AREA) INDEXTYPE IS MDSYS.SPATIAL_INDEX';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

EXIT;
