package io.micronaut.samples.petclinic.repository;

import io.micronaut.context.BeanContext;
import io.micronaut.context.annotation.Requires;
import io.micronaut.data.annotation.Query;
import io.micronaut.inject.BeanDefinition;
import io.micronaut.samples.petclinic.repository.oracle.OracleRepositories;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import jakarta.inject.Inject;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies the Oracle repository SQL generated by Micronaut Data at compile time.
 */
@MicronautTest
@Requires(env = "oracle")
class OracleGeneratedQueryTest {

    @Inject
    BeanContext beanContext;

    @Test
    void generatesNativeOracleBooleanQuery() {
        BeanDefinition<?> beanDefinition = beanContext.getBeanDefinition(
                OracleRepositories.OracleClinicRepository.class);

        String query = beanDefinition
                .getRequiredMethod("existsById", Integer.class)
                .getAnnotationMetadata()
                .stringValue(Query.class)
                .orElseThrow();

        assertThat(query)
                .startsWith("SELECT TRUE FROM")
                .doesNotContain("SELECT 1 FROM");
    }
}
