name: Maven CI

on:
  push:
    branches:
      - main
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - main
      - '[1-9]+.[0-9]+.x'
  workflow_dispatch:

permissions:
  contents: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: JDK ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: ['21', '25']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1.4.1
        with:
          distribution: graalvm
          java-version: ${{ matrix.java-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Maven
        run: ./mvnw -B -ntp -Djdk.version=${{ matrix.java-version }} -Drelease.version=${{ matrix.java-version }} verify

      - name: Publish test report
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          check_name: Maven CI / JDK ${{ matrix.java-version }} / Test Report
          report_paths: |
            **/target/surefire-reports/TEST-*.xml
            **/target/failsafe-reports/TEST-*.xml
          check_retries: 'true'
